language: node_js
node_js:
- '0.10'
- '0.12'
- iojs-1
- iojs-2
- iojs-3
- '4'
- '5'
- '6'
notifications:
  slack:
    secure: spNk3bOknyRzEhT2CTtXCqznok7+Ahraz9ImZPYEyXhUiBGiadZXH++tXUE7TsJVJhf3LdcqfMkEqYbU496AGJVpDnv7J+aaPXP/EwcKhkodMQ8c8U5HMLhhnT0Dxv95ZGBwaFJorb1kvoG6zrVQd3G+gz3hTHNWOZiFrkkvdgga71b9UfkC7Rze1xYW8KXpkyRWai0VUj1Y8hgvoHrDWrMguy0Zbk4XQXatiyF9ckWMQIIkSDddyS4dLYlr5lMQzD3EJkvhdIqQneXKimhW3GpcYQN9tWE/dyFExtZ2zhzRfFtjPpT35IXWWxz7mORx2stqH2VZ+Cig0TIDwe3NRa4MKWtl5R/lG6lJ9z5k/kIhGA92Jo/bV28/3ms7TCOeA6uzka4du/Unr6vwKQ1vLKXESf/HtkjsodnvjpAQAYDUFQD9GGIQ+Nm7x3xDsw4KA7SUDFyquwoCdAUC0FDmucpkQQuAezjS2tWK53bVMBygml6gA+G7goF/u+JIUeZuCo0jjb4p9NQFPGbtzoix7aiO/f01h+PUhsED/WQxBbLYtaM3dPSjxGcbXFipnw5iulDbG71y9+XlBgt4nCtM30rkUmjIbje0T8d7fK0bO+CZ8LY8p1eMvKHiGgmmtYFQypmMAzTWFDQZuD+ErkfLciOp05hXehBBRFbaqdLCGpk=
